// CodeGear C++Builder
// Copyright (c) 1995, 2007 by CodeGear
// All rights reserved

// (DO NOT EDIT: machine generated header) 'Sskinprops.pas' rev: 11.00

#ifndef SskinpropsHPP
#define SskinpropsHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member functions
#pragma pack(push,8)
#include <System.hpp>	// Pascal unit
#include <Sysinit.hpp>	// Pascal unit
#include <Stdctrls.hpp>	// Pascal unit
#include <Sconst.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Sskinprops
{
//-- type declarations -------------------------------------------------------
typedef AnsiString sSkinProps__1[4][4];

typedef AnsiString sSkinProps__2[4];

typedef AnsiString sSkinProps__3[4];

typedef AnsiString sSkinProps__4[4];

typedef AnsiString sSkinProps__5[2];

typedef AnsiString sSkinProps__6[2];

typedef AnsiString sSkinProps__7[3];

typedef AnsiString sSkinProps__8[3];

//-- var, const, procedure ---------------------------------------------------
#define s_BordersMask "BORDERSMASK"
#define s_OuterMask "OUTERMASK"
#define s_ExBorder "EXBORDER"
#define s_LightRegion "LRGN"
#define s_Glow "GLOW"
#define s_GlowMargin "GLOWMARGIN"
#define s_GripImage "GRIPIMAGE"
#define s_GripHorz "GRIPHORZ"
#define s_GripVert "GRIPVERT"
#define s_StatusPanelMask "STATUSPANELMASK"
#define s_ImgTopLeft "IMGTOPLEFT"
#define s_ImgTopRight "IMGTOPRIGHT"
#define s_ImgBottomLeft "IMGBTMLEFT"
#define s_ImgBottomRight "IMGBTMRIGHT"
#define s_NormalTitleBar "TITLEBAR"
#define s_BorderIconClose "BICONCLOSE"
#define s_BorderIconCloseAlone "BICLOSEALONE"
#define s_BorderIconMaximize "BICONMAX"
#define s_BorderIconNormalize "BICONNORM"
#define s_BorderIconMinimize "BICONMIN"
#define s_BorderIconHelp "BICONHELP"
#define s_TitleButtonMask "TITLEBUTTON"
#define s_SmallIconNormalize "SICONNORM"
#define s_SmallIconMinimize "SICONMIN"
#define s_SmallIconMaximize "SICONMAX"
#define s_SmallIconClose "SICONCLOSE"
#define s_SmallIconHelp "SICONHELP"
#define s_SliderChannelMask "SLIDERCHANNEL"
#define s_ItemGlyph "GLYPHMASK"
#define s_SliderHorzMask "SLIDERMASK"
#define s_SliderVertMask "SLIDERVMASK"
#define s_TickVert "TICKVERT"
#define s_TickHorz "TICKHORZ"
#define s_ProgVert "PROGVERT"
#define s_ProgHorz "PROGHORZ"
#define s_NA "N/A"
#define s_ParentClass "PARENTCLASS"
#define s_ReservedBoolean "RESERVEDBOOLEAN"
#define s_GiveOwnFont "GIVEOWNFONT"
#define s_ShiftOnClick "SHIFTCLICK"
#define s_ShowFocus "SHOWFOCUS"
#define s_UseState2 "USESTATE2"
#define s_FontColor "FONTCOLOR"
#define s_TCLeft "TCLEFT"
#define s_TCTop "TCTOP"
#define s_TCRight "TCRIGHT"
#define s_TCBottom "TCBOTTOM"
#define s_Color "COLOR"
#define s_Transparency "TRANSPARENCY"
#define s_GradientPercent "GRADIENTPERCENT"
#define s_GradientData "GRADIENTDATA"
#define s_ImagePercent "IMAGEPERCENT"
#define s_Pattern "PATTERN"
#define s_GlowColor "GCOL"
#define s_GlowSize "GSIZE"
#define s_HotFontColor "HOTFONTCOLOR"
#define s_HotTCLeft "HOTTCLEFT"
#define s_HotTCTop "HOTTCTOP"
#define s_HotTCRight "HOTTCRIGHT"
#define s_HotTCBottom "HOTTCBOTTOM"
#define s_HotColor "HOTCOLOR"
#define s_HotTransparency "HOTTRANSPARENCY"
#define s_HotGradientPercent "HOTGRADIENTPERCENT"
#define s_HotGradientData "HOTGRADIENTDATA"
#define s_HotImagePercent "HOTIMAGEPERCENT"
#define s_HotPattern "HOTPATTERN"
#define s_HotGlowColor "HGCOL"
#define s_HotGlowSize "HGSIZE"
#define s_FontColor2 "FONTCOLOR2"
#define s_TCLeft2 "TCLEFT2"
#define s_TCTop2 "TCTOP2"
#define s_TCRight2 "TCRIGHT2"
#define s_TCBottom2 "TCBOTTOM2"
#define s_Color2 "COLOR2"
#define s_Transparency2 "TRANSPARENCY2"
#define s_GradientPercent2 "GRADIENTPERCENT2"
#define s_GradientData2 "GRADIENTDATA2"
#define s_ImagePercent2 "IMAGEPERCENT2"
#define s_Pattern2 "PATTERN2"
#define s_GlowColor2 "GCOL2"
#define s_GlowSize2 "GSIZE2"
#define s_BorderColor1 "BORDERCOLOR1"
#define s_BorderColor2 "BORDERCOLOR2"
#define s_BorderWidth "BORDERWIDTH"
#define s_TitleHeight "TITLEHEIGHT"
#define s_FormOffset "FORMOFFSET"
#define s_ShadowOffset "ALIGNOFFSET"
#define s_ShadowOffsetR "ALIGNOFFSETR"
#define s_ShadowOffsetT "ALIGNOFFSETT"
#define s_ShadowOffsetB "ALIGNOFFSETB"
#define s_WndShadowRadius "WSHRAD"
#define s_WndShadowOffset "WSHOFFS"
#define s_WndShadowSize "WSHSIZE"
#define s_WndShadowColorN "WSHCOLN"
#define s_WndShadowColorA "WSHCOLA"
#define s_CenterOffset "CENTEROFFSET"
#define s_MaxTitleHeight "MAXHEIGHT"
#define s_BorderMode "BORDERMODE"
#define s_BrightMin "BRIGHTMIN"
#define s_BrightMax "BRIGHTMAX"
#define s_BorderColor "BORDERCOLOR"
#define s_EditTextOk "EDITTEXT_OK"
#define s_EditTextWarning "EDITTEXT_WARN"
#define s_EditTextAlert "EDITTEXT_ALERT"
#define s_EditTextHighlight1 "EDITTEXT_H1"
#define s_EditTextHighlight2 "EDITTEXT_H2"
#define s_EditTextHighlight3 "EDITTEXT_H3"
#define s_EditText_Inverted "EDITTEXT_INV"
#define s_EditBG_Inverted "EDITBG_INV"
#define s_EditBG_OddRow "EDITBG_ODD"
#define s_EditBG_EvenRow "EDITBG_EVEN"
#define s_EditBGOk "EDITBG_OK"
#define s_EditBGWarning "EDITBG_WARN"
#define s_EditBGAlert "EDITBG_ALERT"
#define s_EditGridLine "GRIDLINE"
#define s_MainColor "MAINCOLOR"
#define s_BtnColor1Active "BTNCOLOR1ACTIVE"
#define s_BtnColor2Active "BTNCOLOR2ACTIVE"
#define s_BtnBorderActive "BTNBORDERACTIVE"
#define s_BtnFontActive "BTNFONTACTIVE"
#define s_BtnColor1Normal "BTNCOLOR1NORMAL"
#define s_BtnColor2Normal "BTNCOLOR2NORMAL"
#define s_BtnBorderNormal "BTNBORDERNORMAL"
#define s_BtnFontNormal "BTNFONTNORMAL"
#define s_BtnColor1Pressed "BTNCOLOR1PRESSED"
#define s_BtnColor2Pressed "BTNCOLOR2PRESSED"
#define s_BtnBorderPressed "BTNBORDERPRESSED"
#define s_BtnFontPressed "BTNFONTPRESSED"
#define s_GlobalInfo "GLOBALINFO"
#define s_Transparent "TRANSPARENT"
#define s_Caption "CAPTION"
#define s_FormTitle "FORMTITLE"
#define s_Form "FORM"
#define s_Dialog "DIALOG"
#define s_Hint "HINT"
#define s_MDIArea "MDIAREA"
#define s_MainMenu "MAINMENU"
#define s_MenuItem "MENUITEM"
#define s_Selection "SELECTION"
#define s_MenuIcoLine "ICOLINE"
#define s_MenuExtraLine "EXTRALINE"
#define s_ScrollBar1H "SCROLLBAR1H"
#define s_ScrollBar1V "SCROLLBAR1V"
#define s_ScrollBar2H "SCROLLBAR2H"
#define s_ScrollBar2V "SCROLLBAR2V"
#define s_ScrollSliderV "SCROLLSLIDERV"
#define s_ScrollSliderH "SCROLLSLIDERH"
#define s_ScrollBtnLeft "SCROLLBTNLEFT"
#define s_ScrollBtnTop "SCROLLBTNTOP"
#define s_ScrollBtnRight "SCROLLBTNRIGHT"
#define s_ScrollBtnBottom "SCROLLBTNBOTTOM"
#define s_Divider "DIVIDER"
#define s_DividerV "DIVIDERV"
#define s_ColHeader "COLHEADER"
#define s_ProgressH "PROGRESSH"
#define s_ProgressV "PROGRESSV"
#define s_AlphaEdit "ALPHAEDIT"
#define s_TabTop "TABTOP"
#define s_RibbonTab "RIBBONTAB"
#define s_TabBottom "TABBOTTOM"
#define s_TabLeft "TABLEFT"
#define s_TabRight "TABRIGHT"
#define s_Edit "EDIT"
#define s_ToolButton "TOOLBUTTON"
#define s_ComboBox "COMBOBOX"
#define s_ComboBtn "COMBOBTN"
#define s_AlphaComboBox "ALPHACOMBOBOX"
#define s_ComboNoEdit "COMBONOEDIT"
#define s_UpDown "UPDOWNBTN"
#define s_Button "BUTTON"
#define s_ButtonBig "BUTTON_BIG"
#define s_ButtonHuge "BUTTON_HUGE"
#define s_SpeedButton "SPEEDBUTTON"
#define s_SpeedButton_Small "SPEEDBUTTON_SMALL"
#define s_Panel "PANEL"
#define s_PanelLow "PANEL_LOW"
#define s_TabControl "TABCONTROL"
#define s_PageControl "PAGECONTROL"
#define s_RibbonPage "RIBBONPAGE"
#define s_TabSheet "TABSHEET"
#define s_StatusBar "STATUSBAR"
#define s_ToolBar "TOOLBAR"
#define s_Splitter "SPLITTER"
#define s_GroupBox "GROUPBOX"
#define s_Gauge "GAUGE"
#define s_TrackBar "TRACKBAR"
#define s_CheckBox "CHECKBOX"
#define s_RadioButton "CHECKBOX"
#define s_DragBar "DRAGBAR"
#define s_Bar "BAR"
#define s_BarTitle "BARTITLE"
#define s_BarPanel "BARPANEL"
#define s_WebBtn "WEBBUTTON"
#define s_GripH "GRIPH"
#define s_GripV "GRIPV"
#define s_MenuCaption "MENUCAPTION"
#define s_DialogTitle "DIALOGTITLE"
#define s_MenuButton "MENUBTN"
#define s_MenuLine "MENULINE"
#define s_FormHeader "FORMHEADER"
#define s_TBBtn "TB_BTN"
#define s_TBMenuBtn "TB_MENUBTN"
#define s_TBTab "TB_TAB"
#define s_ColHeaderA "COLHEADERA"
#define s_ColHeaderL "COLHEADERL"
#define s_ColHeaderR "COLHEADERR"
#define s_Slider_Off "SLIDER_OFF"
#define s_Slider_On "SLIDER_ON"
#define s_Thumb_Off "THUMB_OFF"
#define s_Thumb_On "THUMB_ON"
#define s_TabLeftFirst "TABLEFTFIRST"
#define s_TabTopFirst "TABTOPFIRST"
#define s_TabRightFirst "TABRIGHTFIRST"
#define s_TabBottomFirst "TABBOTTOMFIRST"
#define s_TabLeftLast "TABLEFTLAST"
#define s_TabTopLast "TABTOPLAST"
#define s_TabRightLast "TABRIGHTLAST"
#define s_TabBottomLast "TABBOTTOMLAST"
#define s_TabLeftMiddle "TABLEFTMIDDLE"
#define s_TabTopMiddle "TABTOPMIDDLE"
#define s_TabRightMiddle "TABRIGHTMIDDLE"
#define s_TabBottomMiddle "TABBOTTOMMIDDLE"
#define s_MasterBitmap "MASTERBITMAP"
#define s_Preview "PREVIEW"
#define s_CheckGlyph "CHECK"
#define s_CheckBoxChecked "BOXCHECKED"
#define s_CheckBoxUnChecked "BOXUNCHECKED"
#define s_CheckBoxGrayed "BOXGRAYED"
#define s_RadioButtonChecked "RADIOCHECKED"
#define s_RadioButtonUnChecked "RADIOUNCHECKED"
#define s_SmallBoxChecked "SMALLCHECKED"
#define s_SmallBoxUnChecked "SMALLUNCHECKED"
#define s_SmallBoxGrayed "SMALLGRAYED"
#define s_Version "VERSION"
#define s_Author "AUTHOR"
#define s_Description "DESCRIPTION"
#define s_ColorToneRed "COLORTONERED"
#define s_ColorToneGreen "COLORTONEGREEN"
#define s_ColorToneBlue "COLORTONEBLUE"
#define s_ColorToneYellow "COLORTONEYELLOW"
#define s_ColorToneRedActive "COLORTONEREDACTIVE"
#define s_ColorToneGreenActive "COLORTONEGREENACTIVE"
#define s_ColorToneBlueActive "COLORTONEBLUEACTIVE"
#define s_ColorToneYellowActive "COLORTONEYELLOWACTIVE"
#define s_ColorRedText "COLORTONEREDTEXT"
#define s_ColorGreenText "COLORTONEGREENTEXT"
#define s_ColorBlueText "COLORTONEBLUETEXT"
#define s_ColorYellowText "COLORTONEYELLOWTEXT"
#define s_ColorRedTextActive "COLORTONEREDTEXTACTIVE"
#define s_ColorGreenTextActive "COLORTONEGREENTEXTACTIVE"
#define s_ColorBlueTextActive "COLORTONEBLUETEXTActive"
#define s_ColorYellowTextActive "COLORTONEYELLOWTEXTActive"
#define s_Shadow1Color "SHADOW1COLOR"
#define s_Shadow1Offset "SHADOW1OFFSET"
#define s_Shadow1Blur "SHADOW1BLUR"
#define s_Shadow1Transparency "SHADOW1TRANSPARENCY"
#define s_BISpacing "BISPACE"
#define s_BIVAlign "BIVALIGN"
#define s_BIRightMargin "BIRIGHT"
#define s_BILeftMargin "BILEFT"
#define s_BITopMargin "BITOP"
#define s_BIKeepHUE "BIKEEPHUE"
#define s_TabsCovering "TABSCOVERING"
#define s_ArrowLineWidth "ARROWLINE"
#define s_ArrowStyle "ARROWSTYLE"
#define s_States "STATES"
#define s_UseAeroBluring "AEROBLUR"
#define s_ComboMargin "COMBOMARGIN"
#define s_SliderMargin "SLIDERMARGIN"
#define s_OuterOffsL "OUTOFFSL"
#define s_OuterOffsT "OUTOFFST"
#define s_OuterOffsR "OUTOFFSR"
#define s_OuterOffsB "OUTOFFSB"
#define s_OuterMode "OUTERMODE"
#define s_OuterOpacity "OUTOPACITY"
#define s_OuterColorL "OUTCOLL"
#define s_OuterColorT "OUTCOLT"
#define s_OuterColorR "OUTCOLR"
#define s_OuterColorB "OUTCOLB"
#define s_OuterBlur "OUTBLUR"
#define s_OuterRadius "OUTRADIUS"
#define s_ShOERadius "SH_RADIUS_OE"
#define s_LoOERadius "LO_RADIUS_OE"
#define s_ShOEBlur "SH_BLUR_OE"
#define s_LoOEBlur "LO_BLUR_OE"
#define s_ShadowColorL "SH_COLORL"
#define s_ShadowWidthL "SH_WIDTHL"
#define s_ShadowWidthT "SH_WIDTHT"
#define s_ShadowWidthR "SH_WIDTHR"
#define s_ShadowWidthB "SH_WIDTHB"
#define s_ShadowOffsL "SH_OFFSETL"
#define s_ShadowOffsT "SH_OFFSETT"
#define s_ShadowOffsR "SH_OFFSETR"
#define s_ShadowOffsB "SH_OFFSETB"
#define s_ShadowSource "SH_SOURCE"
#define s_ShadowOpacity "SH_OPACITY"
#define s_ShadowMask "SH_MASK"
#define s_LowColorL "LO_COLORL"
#define s_LowColorT "LO_COLORT"
#define s_LowColorR "LO_COLORR"
#define s_LowColorB "LO_COLORB"
#define s_LowWidthL "LO_WIDTHL"
#define s_LowWidthT "LO_WIDTHT"
#define s_LowWidthR "LO_WIDTHR"
#define s_LowWidthB "LO_WIDTHB"
#define s_LowOffsL "LO_OFFSETL"
#define s_LowOffsT "LO_OFFSETT"
#define s_LowOffsR "LO_OFFSETR"
#define s_LowOffsB "LO_OFFSETB"
#define s_LowSource "LO_SOURCE"
#define s_LowOpacity "LO_OPACITY"
#define s_LowMask "LO_MASK"
extern PACKAGE AnsiString acTabSections[4][4];
extern PACKAGE AnsiString acScrollBtns[4];
extern PACKAGE AnsiString acScrollParts[4];
extern PACKAGE AnsiString acUpDownBtns[4];
extern PACKAGE AnsiString acScrollSliders[2];
extern PACKAGE AnsiString acRadioGlyphs[2];
extern PACKAGE AnsiString acCheckGlyphs[3];
extern PACKAGE AnsiString acSmallChecks[3];

}	/* namespace Sskinprops */
using namespace Sskinprops;
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Sskinprops
